#logging:
#  level:
#    com.xupt: debug
#  file: /web.log
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} -%msg%n"
#    file: "%d{yyyy\u2010MM\u2010dd} === [%thread] === %\u20105level === %logger{50} ==== %msg%n"
server:
  port: 8090
  # 配置 tomcat线程的初始数量和等待队列的长度和最大线程的数量
  tomcat:
    accept-count: 1000
    max-threads: 800
    min-spare-threads: 100
    accesslog:
      enabled: true
      directory: /www/miaosha/tomcat
      # 配置日志输出格式 远端主机，u:远端主机的user t:处理时间
      pattern: %h $l %u %t "%r" %s %b %D



first:
  spring:
    datasource:
      url: "jdbc:mysql://127.0.0.1:3306/db_seckill?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false"
      password: root
      username: root
      name: miaosha
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver


spring:
    mail:
      host: stmp.126.com
      username: ityouknow@126.com
      password:
      default-encoding: UTF-8
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
#redis
redis:
  host: 120.79.7.246
  port: 6379
  timeout: 3
  password: admin
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3